<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilos.cssstyle">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="../css/estilos.css">
    <script src="https://kit.fontawesome.com/767382d03b.js" crossorigin="anonymous"></script>
</head>

<body>

    <section>
        <h1 id="main-title">TOPGAMING</a></h1>
    </section>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="home">TOPGAMING</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>home">Home</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>catalogo">Catálogo</a>
                    <a class="nav-link" href="<?= BASE_URL ?>buscarjuego">Juego especifico</a>

                    <a class="nav-link"  href="<?= BASE_URL ?>categorias">Categorías</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>buscarcategoria">Categoría especifica</a>

                    <a class="nav-link"  href="<?= BASE_URL ?>addjuego">Agregar Juego</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>updatejuego">Modificar Juego</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>deletejuego">Eliminar Juego</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>addconsola">Agregar Consola</a>
                    <a class="nav-link"  href="<?= BASE_URL ?>updateconsola">Modificar Consola</a>
                    <a class="nav-link" href="<?= BASE_URL ?>deleteconsola">Eliminar Consola</a>
                    <a class="nav-link"   href="<?= BASE_URL ?>logout">Log Out</a>
                </div>
            </div>
        </div>
    </nav>