

    <?php
    echo "<h2>" . $nombreConsola . "</h2>";
    foreach ($categoriaElegida as $juego) {
        echo "<tr>";
        echo "<td>" . $juego->ID . "</td>";
        echo "<td>" . $juego->nombre . "</td>";
        echo "<td>" . $juego->fecha_lanzamiento . "</td>";
        echo "<td>" . $juego->jugadores . "</td>";
        echo "<td>" . $nombreConsola . "</td>";
       
        echo "</tr>";
        




    } 
    
        ?>
</tbody>
</table>


</body>

</html>